Building Model.
Full Network Model Successfully Built 

Model Built.
Training...
BATCH NUM 0
Traceback (most recent call last):
  File "REU2019/trainingLoop.py", line 152, in <module>
    train_model()
  File "REU2019/trainingLoop.py", line 121, in train_model
    train(epoch)
  File "REU2019/trainingLoop.py", line 70, in train
    output_v1, output_v2, rep_v1, rep_v2 = model(view1vid, view2vid)
  File "/share/apps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yogesh/kara/REU2019/network.py", line 103, in forward
    output_v1 = self.gen(input1)
  File "/share/apps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yogesh/kara/REU2019/generator.py", line 71, in forward
    x = self.upsamp4(x)
  File "/share/apps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/share/apps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/upsampling.py", line 119, in forward
    return F.upsample(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "/share/apps/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1757, in upsample
    return torch._C._nn.upsample_nearest3d(input, _scale_factor(3))
  File "/share/apps/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1729, in _scale_factor
    raise RuntimeError("input aspect ratio doesn't match the output ratio")
RuntimeError: input aspect ratio doesn't match the output ratio
